### ISSUE TITLE
Crashes on death with You're in Grave Danger installed

### ISSUE THREAD

**Issue by ereese99** [BeansGalaxy/Beans-Backpacks-2#79] opened 2024-03-06 19:59 UTC
[message.txt](https://github.com/BeansGalaxy/BeansBackpacks/files/14514884/message.txt)

Upon dying and respawning, I crash. This didn't happen before recent updates.

**Comment by BeansGalaxy** [comment] 2024-03-08 21:05
The issue is with "You're in Grave Danger" due to my latest update. I've already reached out to the mod dev to ensure compatibility in the future.

**Comment by BeansGalaxy** [comment] 2024-03-19 03:15
Closing this issue since I have a duplicate with more info. Thanks for the report!  :~)

**Closed by BeansGalaxy** 2024-03-19 03:15 UTC
Labels: compatibility
