### ISSUE TITLE
Shift-clicking to equip backpack in trinket slot not working in newest version (fabric 1.20.1)

### ISSUE THREAD

**Issue by avilonlegends** [BeansGalaxy/Beans-Backpacks-2#26] opened 2024-01-19 13:09 UTC
Hi again!

In the newest version 1.20.1-0.3-v2 for fabric, it's no longer possible to equip an empty backpack from your inventory in the trinket slot by shift-clicking on the backpack (while sprint is bound to the shift-key). You can only take a backpacked already equipped in the trinket-slot out of it again by shift-clicking.
It worked in version 1.20.1-0.2-v2 for fabric though; perhaps some code got messed up?

**Comment by BeansGalaxy** [comment] 2024-01-19 23:56
All the clicking interactions changed so I must've broke something. I'll check out what might be doing that. Just to be clear, the problem is you cant shift click items into the backpack while sprint is bound to shift and you can only un-equip by shift clicking?

**Comment by BeansGalaxy** [comment] 2024-01-20 04:22
Fixed in 20.1-0.4-v2 & 20.2-0.10-v2.

**Closed by BeansGalaxy** 2024-01-20 04:22 UTC
Labels: bug
