### ISSUE TITLE
[Request] Config option for backpack to only drop as item on death

### ISSUE THREAD

**Issue by avilonlegends** [BeansGalaxy/Beans-Backpacks-2#40] opened 2024-01-29 16:55 UTC
Hi there!

I wanted to ask if perhaps there was a way to add a configuration option to choose whether or not the backpack drops only as an item instead of as an entity. I use the Universal Graves mod, and it does work with your mod, only the backpack entity spawns right in the grave on death, which looks sort of silly ^^"

It's not a big deal or anything, but perhaps such a configuration could make your backpack mod more compatible with other graves mods as well?

**Comment by BeansGalaxy** [comment] 2024-01-29 17:28
The issue is that the player stores all the items in the backpack while worn, not the actual item. So to drop the item I would need to change how the items are stored which would make interacting with other players much more complex. 
Also a big part of this mod is the balancing of the backpacks. I think shulkers replaced the typical modded backpack, and I want mine to seem like an upgrade to the inventory instead of a portable chest. That's why you can't unequip backpacks while there's items inside.

I agree that it looks silly, and I might even add it looks dumb since newer grave mods aren't just a headstone, they're maybe a player skull and text and look really nice, until a backpack gets thrown on top of it. I'll probably drop the backpack to the side like if it was hung when I detect a grave mod installed.

**Comment by BeansGalaxy** [comment] 2024-03-08 21:28
In the latest snapshots they've completely re-worked NBT which makes this highly probable. I'll have to do a full re-write on how the inventory is stored for a port to 1.21 so expect it then but I'll likely not in the current version since it's not really possible. Closing this issue since this can be considered done in the 1.21 version

**Closed by BeansGalaxy** 2024-03-08 21:28 UTC
Labels: enhancement
